#footprint: [[-0.6, -0.6], [-0.6, 0.6], [0.6, 0.6], [0.6, -0.6]]
robot_radius: 0.8485
footprint_padding: 0.01 #0.01 

robot_base_frame: base_link
update_frequency: 7.0 #4.0
publish_frequency: 5.0 #4.0 #3.0
transform_tolerance: 0.5

resolution: 0.05 #0.05

obstacle_range: 6.0 #5.5
raytrace_range: 7.0 #6.0

#layer definitions
static:
    map_topic: /local_grid_obstacle
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser pointcloud
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
    pointcloud: {sensor_frame: frame_name, data_type: PointCloud, topic: local_grid_obstacle, marking: true, clearing: true}
    map_topic: /map
    subscribe_to_updates: true

inflation:
    inflation_radius: 1.13 #1.0 #0.1
