joy_node:
  autorepeat_rate: 30
teleop_twist_joy:
  axis_linear: 1
  scale_linear: 1.0
  scale_linear_turbo: 1.6
  axis_angular: 0
  scale_angular: 0.5
  scale_angular_turbo: 0.65
  enable_turbo_button: 5
  enable_button: 4
